import React from 'react'
import { Routes, Route } from 'react-router-dom'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Home from './Home'
import Programs from './Programs'
import ProgramDetail from './ProgramDetail'
import Trainer from './Trainer'
import Assessment from './Assessment'
import Results from './Results'
import Instagram from './Instagram'
import Contact from './Contact'
import Legal from './Legal'
import NotFound from './NotFound'
export default function App(){return (<div><Header/><main className='mt-16'><Routes><Route path='/' element={<Home/>}/><Route path='/programs' element={<Programs/>}/><Route path='/programs/:slug' element={<ProgramDetail/>}/><Route path='/trainer' element={<Trainer/>}/><Route path='/assessment' element={<Assessment/>}/><Route path='/results' element={<Results/>}/><Route path='/instagram' element={<Instagram/>}/><Route path='/contact' element={<Contact/>}/><Route path='/privacy' element={<Legal kind='privacy'/>}/><Route path='/terms' element={<Legal kind='terms'/>}/><Route path='*' element={<NotFound/>}/></Routes></main><Footer/></div>) }
